<a href="https://colab.research.google.com/github/Rogerio-mack/Analise_de_Dados_2023S2/blob/main/convolucao_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Convolução de um vetor

In [52]:
import numpy as np

# matriz = np.random.randint(0, 10, 10)
vetor = np.arange(0,10)

kernel = np.array([1/3, 1/3, 1/3])

result = np.zeros(len(vetor) - 2)

for i in range(len(result)):
  janela = vetor[i:i+3]  # seleciona a janela 3x
  result[i] = np.sum(janela * kernel)  # aplica a convolução

print(vetor)
print(kernel)
print(result)


[0 1 2 3 4 5 6 7 8 9]
[0.33333333 0.33333333 0.33333333]
[1. 2. 3. 4. 5. 6. 7. 8.]


# Convolução de uma Matriz

In [55]:
import numpy as np

# matriz = np.random.randint(0, 10, (6, 6))
matriz = np.arange(0,36).reshape(6,6)

kernel = np.array([[1/9, 1/9, 1/9],
                   [1/9, 1/9, 1/9],
                   [1/9, 1/9, 1/9]])

result = np.zeros([matriz.shape[0]-2,matriz.shape[1]-2])

for i in range(result.shape[0]):
  for j in range(result.shape[1]):
    janela = matriz[i:i+3, j:j+3]  # seleciona a janela 3x3
    result[i, j] = np.sum(janela * mascara)  # aplica a convolução

print(matriz)
print(kernel)
print(result)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[ 7.  8.  9. 10.]
 [13. 14. 15. 16.]
 [19. 20. 21. 22.]
 [25. 26. 27. 28.]]
