<a href="https://colab.research.google.com/github/Rogerio-mack/Analise_de_Dados_2023S2/blob/main/conv_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
np.random.seed(0)

# vetor = np.random.randint(0, 10, 100)
vetor = np.arange(0,10)

kernel = np.array([1/2, 0, 1/2])

result = np.zeros(len(vetor)-2)

for i in range(1,len(vetor)-1):
#  result[i-1] = vetor[i-1:i+1+1] @ kernel
#  result[i-1] = np.dot(vetor[i-1:i+1+1],kernel)
  result[i-1] = np.sum(vetor[i-1:i+1+1] * kernel)

print(vetor)
print(kernel)
print(result)


[0 1 2 3 4 5 6 7 8 9]
[0.5 0.  0.5]
[1. 2. 3. 4. 5. 6. 7. 8.]
